networks:
  app-net:
    driver: bridge

volumes:
  pg_data:
  mongo_data:
  upload_data:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fs_client
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BROWSER=none
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    command: ["npm", "run", "dev", "--", "--host"]
    networks: [app-net]

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: fs_api
    working_dir: /usr/src/app
    env_file:
      - ./server/.env
      - ./server/.env.development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
    ports:
      - "8080:8080"
      - "5555:5555"   # Prisma Studio (optionnel)
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - upload_data:/usr/src/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    command: ["npm","run","dev:wait"]
    networks: [app-net]

  postgres:
    image: postgres:16-alpine
    container_name: fs_postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [app-net]

  mongo:
    image: mongo:7
    container_name: fs_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks: [app-net]
